#!/bin/sh

ln -sf $HOME/.dotfiles/system/.zshrc.local $HOME/.zshrc.local
ln -sf $HOME/.dotfiles/system/.zshrc $HOME/.zshrc
ln -sf $HOME/.dotfiles/git/gitconfig $HOME/.gitconfig
ln -sf $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
ln -sf $HOME/.dotfiles/system/.aliases $HOME/.aliases
ln -sf $HOME/.dotfiles/system/.functions $HOME/.functions