#!/bin/sh

ln -sf $HOME/.dotfiles/system/.zshrc.local $HOME/.zshrc.local
ln -sf $HOME/.dotfiles/system/.zshrc $HOME/.zshrc
ln -sf $HOME/.dotfiles/system/.aliases $HOME/.aliases
ln -sf $HOME/.dotfiles/system/.functions $HOME/.functions